# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

env:
  PV_DEB: https://github.com/pierre-guillou/paraview-ttk/releases/download/v5.8.0-test/ttk-paraview.deb

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install Ubuntu dependencies
      run: |
        sudo apt update
        # ParaView dependencies
        sudo apt install -y \
          qt5-default \
          qttools5-dev \
          qtxmlpatterns5-dev-tools \
          libqt5x11extras5-dev \
          libqt5svg5-dev \
          dpkg-dev
        # TTK dependencies
        sudo apt install -y \
          libboost-dev \
          libeigen3-dev \
          libgraphviz-dev \
          libsqlite3-dev \
          graphviz \
          python3-sklearn \
          zlib1g-dev

    - name: Install Spectra dependency
      run: |
        git clone --depth 1 https://github.com/yixuan/spectra
        mkdir build_spectra && cd build_spectra
        cmake ../spectra
        sudo make install

    - name: Install ZFP dependency
      run: |
        git clone --depth 1 https://github.com/LLNL/zfp
        mkdir build_zfp && cd build_zfp
        cmake \
          -DBUILD_SHARED_LIBS=OFF \
          -DBUILD_TESTING=OFF \
          ../zfp
        sudo make -j$(nproc) install

    - name: Fetch & install ParaView .deb
      run: |
        wget ${{ env.PV_DEB }}
        sudo dpkg -i ttk-paraview.deb || sudo apt -f install

    - name: Create & configure TTK build directory
      run: |
        mkdir build
        cd build
        cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -DTTK_BUILD_PARAVIEW_PLUGINS=TRUE \
          -DTTK_BUILD_VTK_WRAPPERS=TRUE \
          -DTTK_BUILD_STANDALONE_APPS=TRUE \
          -DTTK_ENABLE_KAMIKAZE=TRUE \
          $GITHUB_WORKSPACE

    - name: Build TTK
      run: |
        cd build
        make -j$(nproc) package

    - name: Upload TTK .deb package
      uses: actions/upload-artifact@v2
      with:
        name: ttk.deb
        path: build/ttk.deb

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Fetch & install ParaView .deb
      run: |
        wget ${{ env.PV_DEB }}
        sudo dpkg -i ttk-paraview.deb || sudo apt -f install

    - name: Fetch TTK .deb artifact
      uses: actions/download-artifact@v2
      with:
        name: ttk.deb

    - name: Install TTK .deb
      run: |
        sudo dpkg -i ttk.deb || sudo apt -f install

    - name: Test TTK examples
      run: |
        export PV_PLUGIN_PATH=/usr/lib/paraview-5.8/plugins/TopologyToolKit
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PV_PLUGIN_PATH
        cd examples/pvpython
        pvpython example.py ../data/inputData.vtu
        cd ../python
        python example.py ../data/inputData.vtu
        cd ../c++
        mkdir build && cd build
        cmake ..
        make
        ./ttkExample-c++ ../../data/inputData.off
        cd ../../vtk-c++
        mkdir build &&  cd build
        cmake ..
        make
        ./ttkExample-vtk-c++ ../../data/inputData.vtu
